# Generated by Django 5.1.4 on 2024-12-23 03:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='exited_time',
        ),
        migrations.RemoveField(
            model_name='table',
            name='no_of_seats',
        ),
        migrations.RemoveField(
            model_name='table',
            name='scanned_time',
        ),
        migrations.RemoveField(
            model_name='table',
            name='table_no',
        ),
        migrations.AddField(
            model_name='table',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
        migrations.AlterField(
            model_name='table',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
